services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    env_file:
      - .env
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
  vc-payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vc-payment-gateway
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
      - MONGODB_CONNECT_URL=mongodb://mongodb:27017/
